#!/usr/bin/env bash
# configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sudo echo '127.0.0.2	localhost' | tee  ~/hosts.new
sudo echo '8.8.8.8	facebook.com' | tee -a ~/hosts.new
cp -f ~/hosts.new /etc/hosts
